### PR TITLE
Update GA for release (closes #666, closes #670).

### LINKED ISSUE #666: Git Flow: release branch
**Describe the feature you'd like**
CD entails a lot of additional compilations (Conda and Docker) which can severely impact the time needed for test to succeed (and hence the general 'coding' flow). I propose to only build and test the software on develop and have periodic merges of develop with release, where
- the PR's from develop to release are tested for Conda and Docker builds
- on push to release, the resulting Conda and Docker builds are deployed to Anaconda cloud and Docker hub.

Once this is in place, we could easily start tagging our releases if we would choose to do so.

### LINKED ISSUE #670: std::any errors
**Describe the bug**
The Conda build logs of PR #666 document that the current build with GNU 9.3.0 has problems using std::any:

```
bld/gqcp_1599474307839/work/gqcp/src/Basis/Integrals/IntegralEngine.cpp:18:
/home/runner/miniconda/envs/packaging/conda-bld/gqcp_1599474307839/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/include/libint2/util/any.h:34:12: error: 'std::any' has not been declared
   34 | using std::any; 
```

The 'standard' build/test and Docker build use GNU 7.5.0 and report no such error.

### PR DESCRIPTION
**Pull request by guacke**
**Short description**
This PR will provide a framework for releases, where Conda/Docker images are built on pull_request and deployed on merge.

### CODE REVIEW

**Comment by lelemmen** [comment]
@guacke Could you use [Github's closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) **in this PR's body** to indicate that this PR closes #666?

**Review by dariatols — APPROVED** [review]

File: gqcp/CMakeLists.txt [hunk 1]
```diff
@@ -5,7 +5,7 @@ target_compile_options(gqcp PUBLIC -m64 -pipe)
 target_compile_options(gqcp PUBLIC "$<IF:$<CONFIG:Debug>,-g,-O2>")
 target_compile_options(gqcp PUBLIC "$<$<CXX_COMPILER_ID:GNU>:-pthread>")
 target_link_options(gqcp PUBLIC "$<$<CXX_COMPILER_ID:GNU>:-pthread>")
-target_compile_features(gqcp PUBLIC cxx_std_11)
```
Comment (lelemmen) [inline gqcp/CMakeLists.txt:8]: Why did we need the upgrade from C++14 to C++11?

File: gqcp/include/Basis/Integrals/BaseOneElectronIntegralBuffer.hpp [hunk 2]
```diff
@@ -19,7 +19,6 @@
 
 
 #include "Mathematical/Representation/Matrix.hpp"
-
```
Comment (lelemmen) [inline gqcp/include/Basis/Integrals/BaseOneElectronIntegralBuffer.hpp:22]: Please set-up your VS Code to use the `clang-format` file for automatic formatting. The setup can be found on our website.
