### ISSUE TITLE
std::any errors

### ISSUE THREAD

**Issue by guacke** [GQCG/GQCP#670]
**Describe the bug**
The Conda build logs of PR #666 document that the current build with GNU 9.3.0 has problems using std::any:

```
bld/gqcp_1599474307839/work/gqcp/src/Basis/Integrals/IntegralEngine.cpp:18:
/home/runner/miniconda/envs/packaging/conda-bld/gqcp_1599474307839/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/include/libint2/util/any.h:34:12: error: 'std::any' has not been declared
   34 | using std::any; 
```

The 'standard' build/test and Docker build use GNU 7.5.0 and report no such error.

**Comment by lelemmen** [comment]
Since `std::any` is C++17, the error is not on GQCP's side (we're only at C++11, but I guess we could modernize our code by using C++17). 

From your error, it's Libint that is trying to use `std::any`, in the header where it defines its own custom implementation. Maybe Libint isn't being compiled with the C++11 STL?

**Comment by guacke** [comment]
Info: C++17 requires including the `<any>` header: https://en.cppreference.com/w/cpp/utility/any.

**Comment by lelemmen** [comment]
Isn't it the other way around? Including the `any` requires C++17?
